### ISSUE TITLE
Criar assets do projeto

### ISSUE THREAD

**Issue by JoaoRafa19** [planemath/planemath#2]
#Criar assets

# Criar e buscar assets para o projeto

## Buscar assets do avião
    

- [x] Voando
- [x] Parado
- [x] Quebrado
- [x] Caindo ( opcional )

- [x] Animação explosão do avião

## Inclui

  

- [x]  Assets do avião
        
- [x]  Assets dos obstáculos
- [x]  Fontes do projeto
- [x]  Backgrounds ( Se possível por nível ) [ Parallax Background ] 
- [x]  Musicas 
- [x]  Sound Effects
- [x]  Spritesheet da animação do avião 

##

**Comment by JoaoRafa19** [comment]
[background](https://drive.google.com/drive/folders/1xHE35CbAVueTnbw7FBIgJi9cSBF-PkUq?usp=drive_link)

**Comment by JoaoRafa19** [comment]
https://itch.io/game-assets/free/tag-sprites

**Comment by dgzim** [comment]
[Musicas](https://drive.google.com/drive/folders/1rrs48Y8SvE4R28mVk1fFGpJDTCSXr7mJ?usp=drive_link)

**Comment by dgzim** [comment]
[Sound effects ](https://drive.google.com/drive/folders/1DS6BPynaX5i-gt9YONDKsvpdkbb5QQZN?usp=drive_link)

**Comment by dgzim** [comment]
[Fontes](https://drive.google.com/drive/folders/1cezdNuGU5r7VOVrXnr_7B5UtanS8oWCu?usp=drive_link)
